### ISSUE TITLE
Fix null reference error during assessment

### ISSUE THREAD

**Issue by Eruanion** [aws/porting-assistant-dotnet-visual-studio-ide-extension#195]
"[2022-01-11 13:54:54 ERR] (Porting Assistant IDE Extension) (1.1.3) PortingAssistantExtensionServer.Services.AnalysisService: incremental assessment failed with error: System.NullReferenceException: Object reference not set to an instance of an object. at PortingAssistant.Client.Analysis.PortingAssistantAnalysisHandler.AnalyzeFileActionsIncremental(String project, RootNodes rootNodes, String targetFramework, String pathToSolution, String filePath, IDEProjectResult projectResult) at PortingAssistant.Client.Analysis.PortingAssistantAnalysisHandler.AnalyzeFileIncremental(String filePath, String fileContent, String projectFile, String solutionFilePath, List`1 preportReferences, List`1 currentReferences, RootNodes projectRules, ExternalReferences externalReferences, Boolean actionsOnly, Boolean compatibleOnly, String targetFramework) at PortingAssistant.Client.Client.PortingAssistantClient.AnalyzeFileAsync(String filePath, String fileContent, String projectFile, String solutionFilePath, List`1 preportReferences, List`1 currentReferences, RootNodes rules, ExternalReferences externalReferences, AnalyzerSettings settings) at PortingAssistantExtensionServer.Services.AnalysisService.AssessFileAsync(CodeFileDocument codeFile, Boolean actionsOnly) in C:\\codebuild\\tmp\\output\\src907355887\\src\\[github.com](http://github.com/)\\aws\\porting-assistant-dotnet-visual-studio-ide-extension\\src\\PortingAssistantExtensionServer\\Services\\AnalysisService.cs:line 162"

**Comment by jonlouie** [comment]
Looks fixed. Re-opened if the issue persists
