### ISSUE TITLE
Porting Assistant extension fails after closing and reopening solution

### ISSUE THREAD

**Issue by duncancoppedge** [aws/porting-assistant-dotnet-visual-studio-ide-extension#207]
On Visual Studio 2022 Version 17.1.2, Windows 10 Pro 19044.1586

## Repro: 

1. Install Porting Assistant vs2022 Extension ;)
2. Open Visual Studio, Create New .Net Framework Project v4.7.2
- In Porting Assistant menu, add settings, target .Net 6.0 and relevant creds
- Run Full Assessment
- Close solution
- Reopen solution
  - Get Error `Activating language client: Porting Assistant`
  - `Your task failed with the message: The type initializer for 'PortingAssistantVSExtensionClient.Options.UserSettings' threw an exception`
  - 
![image](https://user-images.githubusercontent.com/2111973/160171159-9f519047-ea9e-47ea-a86d-6131624684b6.png)
Also get error trying to access the porting assistant settings
![image](https://user-images.githubusercontent.com/2111973/160171342-faab48f1-4c75-4fb0-a646-390d8f0963c6.png)

## Workaround
- In project folder, delete the `.vs` folder
- Everything works again until you close the solution.

**Comment by fbouteruche** [comment]
I get the exact same error

**Comment by huawenm** [comment]
@duncancoppedge  Sorry for the delay, we have identified the issue and fixed it in the latest version. please try with our porting assistant version on 1.1.8. Or if you have turned on auto upgrade in visual studio, you can close the visual studio and reopen it to run upgrade in the background. Thanks again for report this issue and using the porting assistant!

**Comment by jonlouie** [comment]
Fixed by #213

**Comment by duncancoppedge** [comment]
Thanks, tested and working for me on v1.1.8 👍
