### ISSUE TITLE
LSP client performing an invalid cast

### ISSUE THREAD

**Issue by davkean** [aws/porting-assistant-dotnet-visual-studio-ide-extension#367]
Folks, I'm from the Visual Studio reliability team at @ Microsoft. Our telemetry has caught an issue where Porting Assistant extension is performing an invalid cast here: 

https://github.com/aws/porting-assistant-dotnet-visual-studio-ide-extension/blob/1edd8fd4bb0f2308451822704ffd630f82153ca5/src/PortingAssistantExtensionClientShared/PortingAssistantLanguageClient.cs#L275

This issue has been hit almost 200,000 times over the past 21 days, sometimes hundreds a times a Visual Studio session.

```
Unable to cast object of type 'System.Threading.Tasks.Task' to type 'System.Threading.Tasks.Task`1[Microsoft.VisualStudio.LanguageServer.Client.InitializationFailureContext]'
```

Please change this code to something like:

``` C#
InitializationFailureContext initializationFailureContext = new()
{
    FailureMessage = ...
};
        
return Task.FromResult<InitializationFailureContext?>(initializationFailureContext);
```

**Comment by pranav-firake** [comment]
Thanks David for identifying above issue. We are looking into fixing it.
